/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.TransaksiController;
import Model.TransaksiModel;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author Acer
 */
public class TransaksiAdmin extends javax.swing.JFrame {

    private TransaksiController transaksiController;

    /**
     * Creates new form Transaksi
     */
    public TransaksiAdmin() {
        transaksiController = new TransaksiController();
        initComponents();
        loadDataTransaksi();
    }

    private void loadDataTransaksi() {
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Kode Pemesanan");
        tableModel.addColumn("Pemesan");
        tableModel.addColumn("Nomor Kamar");
        tableModel.addColumn("Check-In");
        tableModel.addColumn("Check-Out");
        tableModel.addColumn("Pembayaran");
        tableModel.addColumn("Dibayarkan");

        // Ambil data transaksi dari controller
        List<TransaksiModel> transaksiList = transaksiController.getAllTransaksi();
        for (TransaksiModel transaksi : transaksiList) {
            Object[] rowData = {
                transaksi.getKodePemesanan(),
                transaksi.getPemesan(),
                transaksi.getNomorKamar(),
                transaksi.getCheckIn(),
                transaksi.getCheckOut(),
                transaksi.getPembayaran(),
                transaksi.getDibayarkan()
            };
            tableModel.addRow(rowData);
        }

        // Terapkan model tabel pada jTable1
        tblTransaksi.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Data Transaksi");

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTransaksi);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKembali)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(352, 352, 352))
            .addGroup(layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(btnEdit)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKembali)
                    .addComponent(jLabel1))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblTransaksi.getSelectedRow();
        if (selectedRow != -1) {
            String kodePemesanan = (String) tblTransaksi.getValueAt(selectedRow, 0);
            TransaksiModel transaksi = transaksiController.getTransaksiByKodePemesanan(kodePemesanan);
            if (transaksi != null) {
                String newPemesan = JOptionPane.showInputDialog(this, "Masukkan Pemesan:", transaksi.getPemesan());
                String newNomorKamarStr = JOptionPane.showInputDialog(this, "Masukkan Nomor Kamar:", String.valueOf(transaksi.getNomorKamar()));
                int newNomorKamar = Integer.parseInt(newNomorKamarStr);
                String newCheckIn = JOptionPane.showInputDialog(this, "Masukkan Check-In:", transaksi.getCheckIn());
                String newCheckOut = JOptionPane.showInputDialog(this, "Masukkan Check-Out:", transaksi.getCheckOut());
                String newPembayaran = JOptionPane.showInputDialog(this, "Masukkan Pembayaran:", transaksi.getPembayaran());
                String newDibayarkanStr = JOptionPane.showInputDialog(this, "Masukkan Dibayarkan:", String.valueOf(transaksi.getDibayarkan()));
                int newDibayarkan = Integer.parseInt(newDibayarkanStr);

                transaksi.setPemesan(newPemesan);
                transaksi.setNomorKamar(String.valueOf(newNomorKamar)); // Convert to String
                transaksi.setCheckIn(newCheckIn);
                transaksi.setCheckOut(newCheckOut);
                transaksi.setPembayaran(newPembayaran);
                transaksi.setDibayarkan(newDibayarkan);

                transaksiController.updateTransaksi(transaksi);
                loadDataTransaksi();
            }
        } else {
             JOptionPane.showMessageDialog(this, "Pilih salah satu Data Transaksi untuk diedit.");
}
        

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblTransaksi.getSelectedRow();
if (selectedRow != -1) {
    String kodePemesanan = (String) tblTransaksi.getValueAt(selectedRow, 0);
    TransaksiModel transaksi = transaksiController.getTransaksiByKodePemesanan(kodePemesanan);
    if (transaksi != null) {
        String newPemesan = JOptionPane.showInputDialog(this, "Masukkan Pemesan:", transaksi.getPemesan());
        String newNomorKamarStr = JOptionPane.showInputDialog(this, "Masukkan Nomor Kamar:", String.valueOf(transaksi.getNomorKamar()));
        int newNomorKamar = Integer.parseInt(newNomorKamarStr);
        String newCheckIn = JOptionPane.showInputDialog(this, "Masukkan Check-In:", transaksi.getCheckIn());
        String newCheckOut = JOptionPane.showInputDialog(this, "Masukkan Check-Out:", transaksi.getCheckOut());
        String newPembayaran = JOptionPane.showInputDialog(this, "Masukkan Pembayaran:", transaksi.getPembayaran());
        String newDibayarkanStr = JOptionPane.showInputDialog(this, "Masukkan Dibayarkan:", String.valueOf(transaksi.getDibayarkan()));
        int newDibayarkan = Integer.parseInt(newDibayarkanStr);

        transaksi.setPemesan(newPemesan);
        transaksi.setNomorKamar(String.valueOf(newNomorKamar)); // Convert to String
        transaksi.setCheckIn(newCheckIn);
        transaksi.setCheckOut(newCheckOut);
        transaksi.setPembayaran(newPembayaran);
        transaksi.setDibayarkan(newDibayarkan);

        transaksiController.updateTransaksi(transaksi);
        loadDataTransaksi();
    }
} else {
    JOptionPane.showMessageDialog(this, "Pilih salah satu Data Transaksi untuk diupdate.");
}

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblTransaksi.getSelectedRow();
if (selectedRow != -1) {
    int confirmDialogResult = JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus data transaksi ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
    if (confirmDialogResult == JOptionPane.YES_OPTION) {
        String kodePemesanan = (String) tblTransaksi.getValueAt(selectedRow, 0);
        transaksiController.deleteTransaksi(kodePemesanan);
        loadDataTransaksi(); // Memuat ulang data setelah menghapus transaksi
    }
} else {
    JOptionPane.showMessageDialog(this, "Pilih salah satu Data Transaksi untuk dihapus.");
}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        MainMenu mnu = new MainMenu ();
        TransaksiAdmin trs = new TransaksiAdmin ();
        trs.setVisible(false);
        mnu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTransaksi;
    // End of variables declaration//GEN-END:variables
}
